### ISSUE TITLE
MessageSeen event is not triggering on new message read, if did not answer previous messages

### ISSUE THREAD

**Issue by victorz-airsoft** [rpaschoal/ng-chat#168] opened 2020-07-19 10:23 UTC
Hi, we have got another small issue - if we don't write the reply, when getting the new messages in the opened chat window, "MessagesSeen" ebent does not trigger, when we click the "Type a new message" input. Event will trigger only if we have answered the previous messages by our own message, in other cases it does not trigger. Put some screenshots for the issue

![messageSeenWasTriggered](https://user-images.githubusercontent.com/54435788/87872635-08b35e80-c9c3-11ea-9e1b-b9e0fd27ab54.PNG)
![messageSeenWasNotTriggered](https://user-images.githubusercontent.com/54435788/87872636-0ea93f80-c9c3-11ea-9e6b-680f0f50632f.PNG)

**Comment by rpaschoal** [comment] 2020-07-22 20:41
Closing this as a duplicate of https://github.com/rpaschoal/ng-chat/issues/167

**Closed by rpaschoal** 2020-07-22 20:41 UTC
